version: "3.8"

services:

  #################################
  # Room: The Room microservice
  #################################
  room:
    image: aletheatohh/room:1.0
    restart: always
    environment:
      MYSQL_DB_LINK: jdbc:mysql://mysql-room:3306/roomdb
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"

  #################################
  # MySQL: The official image for MySQL
  #################################
  db:
    container_name: mysql-room
    image: mysql
    restart: always
    environment:
      MYSQL_PASSWORD: ESDT5
      MYSQL_DATABASE: roomdb
      MYSQL_ROOT_PASSWORD: ESDT5
      MYSQL_USER: IS213Room
    expose:
      - "3306"

